name: Publish packages

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    name: Build and publish packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Build packages
        run: pnpm build

      - name: Seed version
        run: |
          set -eo pipefail

          echo "github.ref = '${{ github.ref }}'"
          version=$(echo ${{ github.ref }} | sed 's/^v//')
          echo "VERSION=$version" >> "$GITHUB_ENV"

      - name: Publish packages
        run: |
          set -eo pipefail

          for pkg in packages/*; do
            sed "s/0.0.0/$VERSION/" packages/$pkg/package.json
            pnpm publish
          done

        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
